name: Main workflow

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: Dependency installation
        run: npm ci

      - name: Lint scripts
        run: npm run lint

      - name: Checking file name convention
        run: npm run lint-names

      - name: Integration tests
        run: npm run test

      - name: Checking typescript types and build app
        run: npm run build

      - name: Run prepublish script
        run: npm run prepublish

      # semantic-release release only from master branch, so do not be worry
      - name: Publish to NPM
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
