name: Main workflow

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Dependency installation
        run: npm ci

      - name: Lint scripts
        run: npm run lint

      - name: Checking file name convention
        run: npm run lint-names

      - name: Integration tests
        run: npm run test

      - name: Run prepublish script
        run: npm run prepublish

      # semantic-release release only from master branch, so do not be worry
      - name: Publish to NPM
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
